site_name: FOC 笔记

repo_url: https://github.com/GKbytes/ReadtheDocs
edit_uri: ""

nav:
   - 主页: index.md
   - 建站: 如何建站/ReadtheDocs.md
   - ESC of sensorless BLDC: 
                           - ESC of sensorless BLDC: ESC of sensorless BLDC/三个基本定则.md
   - Vesc: 
        - 了解Vesc: Vesc/了解Vesc.md
        - Vesc-bldc 环境到编译再到下载: Vesc/Vesc-bldc 环境到编译再到下载.md
   - 关于:
        - 许可: about/license.md
# 加入css后，各种屏幕都能适应。
extra_css:
    - css/extra.css




copyright: Copyright &copy; 2020-2030 Gkbytes All Rights Reserved.

# theme: readthedocs
